spring.application.name=ShoeShopBackEnd
# MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/shoeshop
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# JWT config
jwt.secret=0123456789012345678901234567890123456789012345678901234567890123_na_na_na_na_anh_phung_thanh_do
jwt.expiration-ms=86400000

#email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=trungquyen1502@gmail.com
spring.mail.password=jwur ftbs wiwn xedb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
